# Generated by Django 3.2.7 on 2021-09-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_auto_20210920_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={},
        ),
    ]
