# Generated by Django 3.2.7 on 2021-09-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0010_imagemenu_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemenu',
            options={'verbose_name': 'Фото меню', 'verbose_name_plural': 'Фото меню'},
        ),
        migrations.AlterField(
            model_name='mainpageconfig',
            name='gallery_title',
            field=models.CharField(max_length=50, verbose_name='Заголовок галлереи'),
        ),
    ]
