# Generated by Django 3.2.7 on 2021-09-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0011_auto_20210921_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='config',
        ),
        migrations.AddField(
            model_name='mainpageconfig',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='mainpageconfig',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото о клубе'),
        ),
        migrations.AddField(
            model_name='mainpageconfig',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Описание клуба'),
        ),
        migrations.AddField(
            model_name='mainpageconfig',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='mainpageconfig',
            name='schedule',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='imagemenu',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bar.submenu'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайдбара'),
        ),
        migrations.DeleteModel(
            name='AboutInfo',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
