# Generated by Django 3.2.7 on 2021-09-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0012_auto_20210922_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='link',
        ),
    ]
