# Generated by Django 3.2.7 on 2021-09-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0013_remove_slide_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageconfig',
            name='description_search',
            field=models.CharField(default='', max_length=255, verbose_name='Описание для поисковой выдачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpageconfig',
            name='format_detection',
            field=models.CharField(default='', max_length=255, verbose_name='Формат для поисковой выдачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpageconfig',
            name='keywords',
            field=models.CharField(default='', max_length=255, verbose_name='Ключевые слова для поисковой выдачи'),
            preserve_default=False,
        ),
    ]
