# Generated by Django 3.2.7 on 2021-09-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_auto_20210920_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutinfo',
            options={'verbose_name': 'О клубе'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'verbose_name': 'Фотогаллерея'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Сайдбар'},
        ),
    ]
