# Generated by Django 3.2.7 on 2021-09-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0004_alter_contacts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutinfo',
            options={'verbose_name': 'О клубе', 'verbose_name_plural': 'О клубе'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'verbose_name': 'Фотогаллерея', 'verbose_name_plural': 'Фотогаллерея'},
        ),
        migrations.AlterModelOptions(
            name='mainpageconfig',
            options={'verbose_name': 'Конфигурация сайта', 'verbose_name_plural': 'Конфигурация сайта'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Сайдбар', 'verbose_name_plural': 'Сайдбар'},
        ),
    ]
