# Generated by Django 3.2.7 on 2021-09-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0005_auto_20210920_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='title',
        ),
        migrations.AlterField(
            model_name='mainpageconfig',
            name='slide_title',
            field=models.CharField(max_length=255),
        ),
    ]
