# Generated by Django 3.2.7 on 2021-09-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0006_auto_20210920_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото о клубе'),
        ),
        migrations.AlterField(
            model_name='aboutinfo',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Описание клуба'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='schedule',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Галлерея'),
        ),
        migrations.AlterField(
            model_name='mainpageconfig',
            name='about_title',
            field=models.CharField(max_length=15, verbose_name='Заголовок о клубе'),
        ),
        migrations.AlterField(
            model_name='mainpageconfig',
            name='contacts_title',
            field=models.CharField(max_length=15, verbose_name='Заголовок контакты'),
        ),
        migrations.AlterField(
            model_name='mainpageconfig',
            name='gallery_title',
            field=models.CharField(max_length=15, verbose_name='Заголовок галлереи'),
        ),
        migrations.AlterField(
            model_name='mainpageconfig',
            name='slide_title',
            field=models.CharField(max_length=255, verbose_name='Заголовок сайдбара'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото в сайдбар'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Ссылка'),
        ),
    ]
