# Generated by Django 3.2.7 on 2021-09-21 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0008_auto_20210921_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото меню')),
            ],
        ),
        migrations.RemoveField(
            model_name='mainpageconfig',
            name='menu_title',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='config',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок меню'),
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Подзаголовок меню')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.menu')),
            ],
            options={
                'verbose_name': 'Подменю',
                'verbose_name_plural': 'Подменю',
            },
        ),
    ]
