# Generated by Django 3.2.7 on 2021-09-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0009_auto_20210921_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemenu',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.submenu'),
        ),
    ]
