# Generated by Django 3.2.7 on 2021-09-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0014_auto_20210923_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageconfig',
            name='about_title',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Заголовок о клубе'),
        ),
        migrations.AlterField(
            model_name='mainpageconfig',
            name='description_search',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание для поисковой выдачи'),
        ),
        migrations.AlterField(
            model_name='mainpageconfig',
            name='format_detection',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Формат для поисковой выдачи'),
        ),
        migrations.AlterField(
            model_name='mainpageconfig',
            name='gallery_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок галлереи'),
        ),
        migrations.AlterField(
            model_name='mainpageconfig',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова для поисковой выдачи'),
        ),
        migrations.AlterField(
            model_name='mainpageconfig',
            name='slide_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайдбара'),
        ),
    ]
