# Generated by Django 3.2.7 on 2021-09-25 21:03

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0015_auto_20210923_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpageconfig',
            name='description_search',
        ),
        migrations.RemoveField(
            model_name='mainpageconfig',
            name='format_detection',
        ),
        migrations.RemoveField(
            model_name='mainpageconfig',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='', verbose_name='Галлерея'),
        ),
        migrations.AlterField(
            model_name='imagemenu',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото меню'),
        ),
        migrations.AlterField(
            model_name='mainpageconfig',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='uploaded_images', verbose_name='Фото о клубе'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото в сайдбар'),
        ),
        migrations.CreateModel(
            name='MetaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_search', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание для поисковой выдачи')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова для поисковой выдачи')),
                ('format_detection', models.CharField(blank=True, max_length=255, null=True, verbose_name='Формат для поисковой выдачи')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bar.mainpageconfig')),
            ],
            options={
                'verbose_name': 'Информация для поисковых систем',
                'verbose_name_plural': 'Информация для поисковых систем',
            },
        ),
    ]
